name = "Mechanical Mayhem 2"
author = "Herr Katze"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca5c559e620a1ef0f5e318aeb4f257d5f82ed25a70af96117a48c8fce27766fb"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
