name = "Mechanical Mayhem 2"
author = "Herr Katze"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7a82c13d7c5088377c56e78a7f956d55a0850e8b40837fcf126a7e0db36dc7e"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
