name = "Mechanical Mayhem 2"
author = "Herr Katze"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9342520b09ffd35cce599170ebb789c02c0ea800722478953e3135942b26f9f"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
