name = "Mechanical Mayhem 2"
author = "Herr Katze"
version = "96b8e31"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03b7e5b09de07b5943d531465439ec48b492256e9fbb2aab0c4b9f4219679a7d"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
