name = "Mechanical Mayhem 2"
author = "Maple Modworks"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34ab9068f0417a6997fa0182ce936023d8190ff6ca447be0040a8769f2adc877"

[versions]
forge = "43.3.13"
minecraft = "1.19.2"
