name = "Mechanical Mayhem 2"
author = "Herr Katze"
version = "96b8e31"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a3532782863cbb825070a39a61f5b76e7356712992c8d8e74c8900bb01e8507"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
