name = "Mechanical Mayhem 2"
author = "Maple Modworks"
version = "68daa32"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "588a824e20c82729c3a40e76591b29e83c203116931abc58d81892895e4a3a4c"

[versions]
forge = "43.3.13"
minecraft = "1.19.2"
