name = "Mechanical Mayhem 2"
author = "Maple Modworks"
version = "106ed2c"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9f881826699214544c0c2300e5b637a19969055abac3d24d0873da3e1a756c1"

[versions]
forge = "47.4.1"
minecraft = "1.20.1"
