name = "Mechanical Mayhem 2"
author = "Maple Modworks"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da95dac34479a1c3a0d18aad7cf072ffdfb91bdf569fa78bd721109ade57cb1d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
