name = "Mechanical Mayhem 2"
author = "Maple Modworks"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dfe1f2076d910b4402fb622f5d27ae8cb8b16cb575170a1ed086621baf01939"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
